name: Android CI

on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./android/gradlew 

      # - name: Run gradle tests
      #   working-directory: ./android
      #   run: ./gradlew test

      - name: Build with Gradle
        working-directory: ./android
        run: ./android/gradlew build test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/intermediates/apk/debug/
